version: '3.4'

services:
  new-api:
    build: .  # 从本地构建镜像
    container_name: new-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - SQL_DSN=root:123456@tcp(host.docker.internal:3306)/new-api  # 连接已部署的 MySQL
      - REDIS_CONN_STRING=redis://host.docker.internal:6379  # 连接已部署的 Redis
      - TZ=Asia/Shanghai
      - ERROR_LOG_ENABLED=true
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $$2}'"]
      interval: 30s
      timeout: 10s
      retries: 3
